defaults: &defaults
  qtypes: [["多选", 0],["文本", 1],["单选", 2],["日期", 3],["图片", 4],["多文本", 5]]
  mail_from: "xxxx.com"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
